project:
  type: book

book:
  title: "Decizie și estimare în prelucrarea informației (DEPI)"
  subtitle: "Note de curs"
  author: "Nicolae Cleju"
  date: "05/25/2023"

  chapters:
    - index.qmd
    - 01_Intro.qmd
    - part: "Semnale Aleatoare"
      chapters:
      - 01_01_VariabileAleatoare.qmd
      - 01_02_ProceseAleatoare.qmd
      - 01_03_Autocorelatia.qmd
        #- 01_SemnaleAleatoare.qmd
    - part: "Decizie"
      chapters:
      - 02_01_Detectia1Esantion.qmd
      - 02_02_DetectiaMaiMulteEsantioane.qmd
      - 02_03_AlgoritmiPractici.qmd
    - part: "Estimare"
      chapters:
      - 03_01_Estimare.qmd
    - part: "Aplicații practice"
      chapters:
      - App01_OutlierDetection.ipynb
    #- Shiny.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  # PDF fails because of included .gif file
  # pdf:
  #   documentclass: scrreprt

jupyter: python3

filters:
  - shinylive

execute:
  cache: true
