
# Seminar 06: K-NN, K-Means, estimare ML

## Exercițiul 1: k-NN

1. Fie următorul set de 10 vectori, compus din 5 vectori din clasa A și 5 vectori din clasa B:
    * Clasa A:
$$\mathbf{v}_1 = \begin{bmatrix}2 \\ -4\end{bmatrix}\;
\mathbf{v}_2 = \begin{bmatrix}1 \\ -5\end{bmatrix}\;
\mathbf{v}_3 = \begin{bmatrix}-2 \\ 6\end{bmatrix}\;
\mathbf{v}_4 = \begin{bmatrix}-3 \\ 4\end{bmatrix}\;
\mathbf{v}_5 = \begin{bmatrix}2 \\ -5\end{bmatrix}$$
    * Clasa B:
$$\mathbf{v}_6 = \begin{bmatrix}3 \\ 1\end{bmatrix}\;
\mathbf{v}_7 = \begin{bmatrix}-1 \\ 1\end{bmatrix}\;
\mathbf{v}_8 = \begin{bmatrix}-4 \\ -3\end{bmatrix}\;
\mathbf{v}_9 = \begin{bmatrix}-3 \\ 0\end{bmatrix}\;
\mathbf{v}_{10} = \begin{bmatrix}-2 \\ 3\end{bmatrix}$$

Calculați clasa vectorului $\mathbf{x} = \begin{bmatrix}-2 \\ 5 \end{bmatrix}$
folosind algoritmul k-NN, pentru diverse valori ale lui $k$: $k=1$, $k=3$, $k=5$, $k=7$ și $k=9$

### Rezolvare {.unnumbered}

Pentru a calcula clasa vectorului $\mathbf{x}$ folosind algoritmul k-NN,
trebuie să găsim cei mai apropiați $k$ vecini ai săi din setul de vectori dat
și să determinăm clasa majoritară dintre acești vecini.
Vom face acest lucru pentru fiecare valoare a lui $k$: 1, 3, 5, 7 și 9.

Vecinii se determină folosind distanța Euclidiană între vectori.
$$d(\mathbf{x}, \mathbf{v}_i) = \sqrt{ (x_1 - v_{i1})^2 + (x_2 - v_{i2})^2}$$

Pentru $\mathbf{x} = \begin{bmatrix}-2 \\ 5 \end{bmatrix}$,
distanțele față de vectorii din setul de date sunt:
$$d(\mathbf{x}, \mathbf{v}_1)    = \sqrt{ (-2 - 2)^2  +  (5 + 4)^2} = \sqrt{97}$$
$$d(\mathbf{x}, \mathbf{v}_2)    = \sqrt{ (-2 - 1)^2  +  (5 + 5)^2} = \sqrt{109}$$
$$d(\mathbf{x}, \mathbf{v}_3)    = \sqrt{ (-2 + 2)^2  +  (5 - 6)^2} = \sqrt{1}$$
$$d(\mathbf{x}, \mathbf{v}_4)    = \sqrt{ (-2 + 3)^2  +  (5 - 4)^2} = \sqrt{2}$$
$$d(\mathbf{x}, \mathbf{v}_5)    = \sqrt{ (-2 - 2)^2  +  (5 + 5)^2} = \sqrt{116}$$
$$d(\mathbf{x}, \mathbf{v}_6)    = \sqrt{ (-2 - 3)^2  +  (5 - 1)^2} = \sqrt{41}$$
$$d(\mathbf{x}, \mathbf{v}_7)    = \sqrt{ (-2 + 1)^2  +  (5 - 1)^2} = \sqrt{17}$$
$$d(\mathbf{x}, \mathbf{v}_8)    = \sqrt{ (-2 + 4)^2  +  (5 + 3)^2} = \sqrt{68}$$
$$d(\mathbf{x}, \mathbf{v}_9)    = \sqrt{ (-2 + 3)^2  +  (5 - 0)^2} = \sqrt{26}$$
$$d(\mathbf{x}, \mathbf{v}_{10}) = \sqrt{ (-2 + 2)^2  +  (5 - 3)^2} = \sqrt{4}$$

Aranjăm distanțele în ordine crescătoare:
$$\sqrt{1}, \sqrt{2}, \sqrt{4}, \sqrt{17}, \sqrt{26}, \sqrt{41}, \sqrt{68}, \sqrt{97}, \sqrt{109}, \sqrt{116}$$
care corespund cu următorii vecini ai lui $\mathbf{x}$, de la cel mai apropiat la cel mai îndepărtat:
$$\mathbf{v}_3, \mathbf{v}_4, \mathbf{v}_{10}, \mathbf{v}_7, \mathbf{v}_9, \mathbf{v}_6, \mathbf{v}_8, \mathbf{v}_1, \mathbf{v}_2, \mathbf{v}_5$$

Decizia asupra clasei vectorului $\mathbf{x}$ se ia în funcție de clasa majoritară a celor mai apropiați vecini ai săi, în număr de $k$.

Pentru $k=1$: considerăm doar primul vecin, $\mathbf{v}_3$, din clasa A, deci clasa lui $\mathbf{x}$ este A.

Pentru $k=3$: primii $3$ vecini sunt $\mathbf{v}_3$, $\mathbf{v}_4$ și $\mathbf{v}_{10}$, dintre care doi sunt din clasa A și unul din clasa B, deci clasa lui $\mathbf{x}$ este A.

Pentru $k=5$: vecinii sunt $\mathbf{v}_3$, $\mathbf{v}_4$, $\mathbf{v}_{10}$, $\mathbf{v}_7$ și $\mathbf{v}_9$, dintre care doi sunt din clasa A și trei din clasa B, deci clasa lui $\mathbf{x}$ este B.

Pentru $k=7$: vecinii sunt $\mathbf{v}_3$, $\mathbf{v}_4$, $\mathbf{v}_{10}$, $\mathbf{v}_7$, $\mathbf{v}_9$, $\mathbf{v}_6$ și $\mathbf{v}_8$, dintre care doi sunt din clasa A și cinci din clasa B, deci clasa lui $\mathbf{x}$ este B.

Penru $k=9$: vecinii sunt $\mathbf{v}_3$, $\mathbf{v}_4$, $\mathbf{v}_{10}$, $\mathbf{v}_7$, $\mathbf{v}_9$, $\mathbf{v}_6$, $\mathbf{v}_8$, $\mathbf{v}_1$ și $\mathbf{v}_2$, dintre care patru sunt din clasa A și cinci din B, deci clasa lui $\mathbf{x}$ este B.

## Exercițiul 2: k-Means

Fie următoarele zece valori numerice:
$$\mathbf{v} = \left\lbrace v_i \right\rbrace = [ 1.1, 0.9,
5.5, 0.6, 5, 6, 1.3, 4.8, 6, 0.8 ] $$

Efectuați cinci iterații ale algoritmul k-Means pentru a găsi doi centroizi $\mathbf{c}_1$ și $\mathbf{c}_2$,
pornind de la două valori aleatoare $\mathbf{c}_1 = 0.95$ și $\mathbf{c}_2 = 0.96$.

### Rezolvare {.unnumbered}

Algoritmul k-Means urmărește găsirea a $k$ centroizi care se grupeze datele de intrare
în clustere bine definite.

Algoritmul are următorii pași:

1. Se aleg $k$ centroizi inițiali $\mathbf{c}_1, \mathbf{c}_2, \dots, \mathbf{c}_k$. În cazul nostru, valorile inițiale sunt date: $\mathbf{c}_1 = 0.95$ și $\mathbf{c}_2 = 0.96$.
2. Pentru fiecare vector $\mathbf{v}$ din setul de date, se calculează distanțele față de fiecare centroid,
$d(\mathbf{v}, \mathbf{c}_i)$, și vectorul este asignat centroidului cel mai apropiat.
3. Se recalculează centroizii ca fiind media vectorilor care au fost asignați fiecărui centroid în parte
4. Se repetă pașii 2-4 până când centroizii nu se mai modifică, sau se atinge numărul maxim de iterații.

În cazul nostru, avem $k=2$ și $N=10$ vectori de intrare (numerele individuale).

La iterația 1:

- numerele asignate lui $c_1 = 0.95$ sunt: $[0.9, 0.6, 0.8]$, iar cele asignate lui $c_2 = 0.96$ sunt: $[1.1, 5.5, 5, 6, 1.3, 4.8, 6]$
- recalculăm centroizii:
  $$c_1 = \frac{0.9 + 0.6 + 0.8}{3} = 0.77$$
  $$c_2 = \frac{1.1 + 5.5 + 5 + 6 + 1.3 + 4.8 + 6}{7} = 4.2$$

La iterația 2:

- numerele asignate lui $c_1 = 0.77$ sunt: $[0.9, 0.6, 0.8, 1.1, 1.3]$, iar cele asignate lui $c_2 = 4.2$ sunt: $[5.5, 5, 6, 4.8, 6]$
- recalculăm centroizii:
  $$c_1 = \frac{0.9 + 0.6 + 0.8 + 1.1 + 1.3}{5} = 0.94$$
  $$c_2 = \frac{5.5 + 5 + 6 + 4.8 + 6}{5} = 5.46$$

La iterația 3:

- numerele asignate lui $c_1 = 0.94$ sunt: $[0.9, 0.6, 0.8, 1.1, 1.3]$, iar cele asignate lui $c_2 = 5.46$ sunt: $[5.5, 5, 6, 4.8, 6]$
- recalculăm centroizii:
  $$c_1 = \frac{0.9 + 0.6 + 0.8 + 1.1 + 1.3}{5} = 0.94$$
  $$c_2 = \frac{5.5 + 5 + 6 + 4.8 + 6}{5} = 5.46$$

Se observă că centroizii nu se mai modifică, deci din acest moment iteratițiile pot
fi terminate algoritmul converge.

Rezultatul final este cel de la ultima iterație:

- centroidul $c_1$ este $c_1 = 0.94$ și are asignate numerele $[0.9, 0.6, 0.8, 1.1, 1.3]$
- centroidul $c_2$ este $c_2 = 5.46$ și are asignate numerele $[5.5, 5, 6, 4.8, 6]$

## Exercițiul 3: estimare ML

Se recepționează un semnal constant de amplitudine necunoscută A, afectat de zgomot gaussian, $r(t) = \underbrace{A}_{s_\Theta(t)} + zgomot$,
unde zgomotul este de tip gaussian $\mathcal{N}(\mu = 0, \sigma^2 = 2)$.

Semnalul este eșantionat la momentele $t_i = [0,1.5,3,4]$ și se observă valorile $r_i = [4.6, 5.2, 5.35, 4.8]$.

Estimați valoarea lui A folosind estimarea Maximum Likelihood

### Rezolvare {.unnumbered}

Întrucât zgomotul este de tip gaussian, estimarea Maximum Likelihood (ML)
se reduce la problema minimizării distanței Euclidiene între semnalul observat și semnalul original.
$$\hat{A}_{ML} = \arg \min_{A} d(\mathbf{r}, \mathbf{s})^2$$

Vectorul observații este cel dat în problemă:
$$\mathbf{r} = [4.6, 5.2, 5.35, 4.8]$$

Vectorul semnalului original este ceea ce ar fi trebuit să observăm
la cele patru momentele de timp $t_i = [0,1.5,3,4]$ dacă nu ar fi existat zgomot,
adică $A$:
$$\mathbf{s} = [A, A, A, A]$$

Distanța Euclidiană la pătrat între cei doi vectori este:
$$d(\mathbf{r}, \mathbf{s}) = (A - 4.6)^2 + (A - 5.2)^2 + (A - 5.35)^2 + (A - 4.8)^2$$

Vrem să găsim valoarea lui $A$ care minimizează această distanță. Pentru aceasta, derivăm expresia după $A$ și o egalam cu 0:
$$\frac{\partial d(\mathbf{r}, \mathbf{s})}{\partial A} =
2 \cdot (A - 4.6) + 2 \cdot (A - 5.2) + 2 \cdot (A - 5.35) + 2 \cdot (A - 4.8) = 0$$

Rezolvând aceasta ecuație, obținem estimarea ML a lui A:
$$\hat{A}_{ML} = \frac{4.6 + 5.2 + 5.35 + 4.8}{4} = 4.9875$$

## Exercițiul 4: estimare ML

Un semnal de forma $r(t) = A \cdot t^2 + 2 + zgomot$ este eșantionat la momentele  $t_i = [1,2,3,4,5]$,
și valorile obținute sunt $r_i = [1.2, 3.7, 8.5, 18, 25.8]$. Distribuția zgomotului este
$\mathcal{N}(0,\sigma^2=1)$.

Estimați parametrul $A$ folosind estimarea ML.

### Rezolvare {.unnumbered}

Singura diferență față de exercițiul anterior este că semnalul original nu mai este constant,
ci este de forma $A \cdot t^2 + 2$.

Așadar, valorile semnalului original la momentele de eșantionare $t_i = [1,2,3,4,5]$ sunt:
$$\mathbf{s} = [A + 2, \;\; 4A + 2, \;\; 9A + 2, \;\; 16A + 2, \;\;25A + 2]$$

Distanța Euclidiană la pătrat între cei doi vectori este:

\begin{aligned}
d(\mathbf{r}, \mathbf{s}) &= (A + 2 - 1.2)^2 + (4A + 2 - 3.7)^2 + (9A + 2 - 8.5)^2 + (16A + 2 - 18)^2 + (25A + 2 - 25.8)^2 \\
&= (A + 0.8)^2 + (4A - 1.7)^2 + (9A - 6.5)^2 + (16A - 16)^2 + (25A - 23.8)^2
\end{aligned}

Derivând expresia după $A$ și o egalam cu 0, obținem estimarea ML a lui A:
$$\frac{\partial d(\mathbf{r}, \mathbf{s})}{\partial A} =
2 \cdot (A + 0.8) + 2 \cdot (4A - 1.7) \cdot 4 + 2 \cdot (9A - 6.5) \cdot 9 + 2 \cdot (16A - 16) \cdot 16 + 2 \cdot (25A - 23.8) \cdot 25 = 0$$

Rezolvând aceasta ecuație, obținem estimarea ML a lui A:
$$\hat{A}_{ML} = \frac{-0.8 + 1.7 \cdot 4 + 6.5 \cdot 9 + 16 \cdot 16 + 23.8 \cdot 25}{1 + 4^2 + 9^2 + 16^2 + 25^2} = 0.93$$

## Exercițiul 5: estimare ML

Valorile măsurate ale unei funcții liniare $y = ax$, unde $a$ este necunoscut, sunt următoarele:
$(x_i, y_i) = {(1,1.8),(2,4.1),(2.5, 5.1),(4,7.9),(4.3, 8.5)}$.
Presupunând că zgomotul are distribuția $\mathcal{N}(0,\sigma^2=1)$, estimați valoarea lui $a$ folosind estimarea ML

### Rezolvare {.unnumbered}

Suntem în același caz ca la exercițiile anterioare, doar că de data aceasta avem
ușor altă formulare a problemei.

În loc sa avem eșantioane din $r(t)$ la momente de timp $t_i$,
avem eșantioane din $y(x)$ la valori ale lui $x_i$.
Așadar, valorile $y_i$ joacă rolul valorilor $r_i$ din exercițiile anterioare,
iar $x_i$ rolul lui $t_i$.

Valorile măsurate sunt cele ale $y_i$:
$$\mathbf{r} = \mathbf{y} = [1.8, 4.1, 5.1, 7.9, 8.5]$$

În absența zgomotului, pentru o funcție liniară $y = ax$, valorile semnalului original la valorile $x_i = [1,2,2.5,4,4.3]$ ar fi fost:
$$\mathbf{s} = [a \cdot 1, \;\; a \cdot 2, \;\; a \cdot 2.5, \;\; a \cdot 4, \;\; a \cdot 4.3]$$

Zgomotul fiind de tip gaussian, estimarea ML înseamnă minimizarea distanței Euclidiene între $\mathbf{r}$ și $\mathbf{s}$:
$$d(\mathbf{r}, \mathbf{s})^2 = (a-1.8)^2 + (2a-4.1)^2 + (2.5a-5.1)^2 + (4a-7.9)^2 + (4.3a-8.5)^2$$

Aflăm minimul expresiei prin derivare și egalare cu 0:
$$\frac{\partial d(\mathbf{r}, \mathbf{s})}{\partial a} = 2 \cdot (a-1.8) + 2 \cdot (2a-4.1) \cdot 2 + 2 \cdot (2.5a-5.1) \cdot 2.5 + 2 \cdot (4a-7.9) \cdot 4 + 2 \cdot (4.3a-8.5) \cdot 4.3 = 0$$

Rezolvând aceasta ecuație, obținem estimarea ML a lui A:
$$\hat{a}_{ML} = \frac{1.8 + 4.1 \cdot 2 + 5.1 \cdot 2.5 + 7.9 \cdot 4 + 8.5 \cdot 4.3}{1 + 4 + 2.5^2 + 16 + 4.3^2} = 2.29$$

## Exercițiul 6: estimare ML cu mai mulți parametri

Un robot se deplasează pe o traiectorie liniară cu o viteză necunoscută $V$ centimetri/secundă,
pornind de la poziția $x = 0$ la momentul inițial.

La intervale de o secundă, robotul măsoară distanța parcursă folosind un senzor, afectat de zgomot gaussian $\mathcal{N}(0,\sigma^2=0.1)$.

Valorile măsurate la momentele $t_i = [1,2,3,4,5]$ sunt $r_i = [4.9, 9.8, 14.3, 21.2, 25.7]$

Cerințe:

a. Estimați viteza $V$ a robotului folosind estimarea ML

   *Hint*: Dacă viteza e constantă, distanta parcursă ar trebui să fie $x = V \cdot t$

b. Preziceți poziția robotului la momentul $6$.

c. Dacă presupunem la momentul inițial poziția robotului nu este 0, ci o valoare necunoscută $x_0$, estimați perechea de parametri [V, $x_0$]
folosind estimarea ML. Preziceți poziția robotului la momentul $6$.

d. Știind că legea de mișcare este $x(t) = \frac{a \cdot t^2}{2} + v_0 \cdot t + x_0$, scrieți sistemul de ecuații pentru găsirea necunoscutelor [a, $v_0$, $x_0$].
(accelerația constantă $a$, viteza inițială $v_0$, poziția inițială$x_0$).

   \smallskip

### Rezolvare {.unnumbered}

Avem de a face cu estimarea ML în zgomot gaussian, deci vom proceda
similar cu exercițiile anterioare.

a. Viteza robotului fiind constantă, poziția sa este dată de legea de mișcare
$$x(t) = V \cdot t$$

    În absența zgomotului, valorile poziției la momentele $t_i = [1,2,3,4,5]$ ar fi fost:
$$\mathbf{s} = [V \;\; 2V, \;\; 3V, \;\; 4V, \;\; 5V],$$
dar valorile observate sunt:
$$\mathbf{r} = [4.9, 9.8, 14.3, 21.2, 25.7]$$

    Distanța Euclidiană la pătrat între cei doi vectori este:
$$d(\mathbf{r}, \mathbf{s})^2 = (V - 4.9)^2 + (2V - 9.8)^2 + (3V - 14.3)^2 + (4V - 21.2)^2 + (5V - 25.7)^2$$
    Derivăm:
$$\frac{\partial d(\mathbf{r}, \mathbf{s})}{\partial V} = 2 \cdot (V - 4.9) + 2 \cdot (2V - 9.8) \cdot 2 + 2 \cdot (3V - 14.3) \cdot 3 + 2 \cdot (4V - 21.2) \cdot 4 + 2 \cdot (5V - 25.7) \cdot 5 = 0$$
și obținem viteza:
$$\hat{V}_{ML} = \frac{4.9 + 9.8 \cdot 2 + 14.3 \cdot 3 + 21.2 \cdot 4 + 25.7 \cdot 5}{1 + 4 + 9 + 16 + 25} = 5.10$$

b. Prezicem poziția la momentul $t=6$ aplicând aceeași lege de mișcare, folosind viteza estimată:
$$x(6) = 5.10 \cdot 6 = 30.6$$

c. Dacă poziția inițială este valoare necunoscută $x_0$, atunci avem de estimat doi parametri: $V$ și $x_0$. Acest lucru se face în mod asemănător, după cum urmează.

    În absența zgomotului, valorile poziției la momentele $t_i = [1,2,3,4,5]$ ar fi fost:
$$\mathbf{s} = [V + x_0, \;\; 2V + x_0, \;\; 3V + x_0, \;\; 4V + x_0, \;\; 5V + x_0],$$
iar distanța pătratică față de valorile observate este:
$$d(\mathbf{r}, \mathbf{s})^2 = (V + x_0 - 4.9)^2 + (2V + x_0 - 9.8)^2 + (3V + x_0 - 14.3)^2 + (4V + x_0 - 21.2)^2 + (5V + x_0 - 25.7)^2$$

    Avem acum o expresie cu două necunoscute, $V$ și $x_0$,
pe care dorim să o minimizăm.
Pentru aceasta derivăm după fiecare dintre ele, egalăm cu 0, și rezolvăm
sistemul de ecuații astfel obținut.

    Avem:
$$
\begin{cases}
\frac{\partial d(\mathbf{r}, \mathbf{s})}{\partial V} = 2 \cdot (V + x_0 - 4.9) + 2 \cdot (2V + x_0 - 9.8) \cdot 2 + 2 \cdot (3V + x_0 - 14.3) \cdot 3 + 2 \cdot (4V + x_0 - 21.2) \cdot 4 + 2 \cdot (5V + x_0 - 25.7) \cdot 5 = 0 \\
\frac{\partial d(\mathbf{r}, \mathbf{s})}{\partial x_0} = 2 \cdot (V + x_0 - 4.9) + 2 \cdot (2V + x_0 - 9.8) + 2 \cdot (3V + x_0 - 14.3) + 2 \cdot (4V + x_0 - 21.2) + 2 \cdot (5V + x_0 - 25.7) = 0
\end{cases}
$$
Simplificând și prelucrând relațiile, obținem:
$$
\begin{cases}
55V + 15x_0 = 280.7 \\
15V + 5x_0 = 75.9
\end{cases}
$$
Rezolvând acest sistem, obținem soluția:
$$\hat{V}_{ML} = 5.3, \;\; \hat{x}_{0,ML} = -0.72$$

    Pentru a estima poziția la momentul $t=6$, folosim aceeași lege de mișcare, cu parametrii estimati:
$$x(6) = V \cdot 6 + x_0 = 5.3 \cdot 6 - 0.72 = 31.08$$

d. La punctul precedent am considerat o viteză constantă, deci accelerația egală cu 0.
În cele ce urmează, considerăm un caz mai general, cu accelerație diferită de 0.

    Legea de mișcare este:
$$x(t) = \frac{a \cdot t^2}{2} + v_0 \cdot t + x_0$$
unde $a$ este accelerația, $v_0$ este viteza inițială, iar $x_0$ este poziția inițială.
Toate cele trei mărimi sunt necunoscute care trebuie estimate.

    În absența zgomotului, valorile poziției la momentele $t_i = [1,2,3,4,5]$ ar fi fost:
$$\mathbf{s} = [\frac{a}{2} + v_0 + x_0, \;\; 2a + 2v_0 + x_0, \;\; \frac{9a}{2} + 3v_0 + x_0, \;\; 8a + 4v_0 + x_0, \;\; \frac{25a}{2} + 5v_0 + x_0],$$
așadar distanța pătratică față de valorile observate este:
$$d(\mathbf{r}, \mathbf{s})^2 = (\frac{a}{2} + v_0 + x_0 - 4.9)^2 + (2a + 2v_0 + x_0 - 9.8)^2 + (\frac{9a}{2} + 3v_0 + x_0 - 14.3)^2 + (8a + 4v_0 + x_0 - 21.2)^2 + (\frac{25a}{2} + 5v_0 + x_0 - 25.7)^2$$

Cele trei derivate parțiale în raport cu necunoscutele formează un sistem de trei ecuații
cu trei necunoscute, pe care îl rezolvăm pentru a obține estimările ML ale parametrilor:
$$
\begin{cases}
\frac{\partial d(\mathbf{r}, \mathbf{s})}{\partial a} = 2 \cdot (\frac{a}{2} + v_0 + x_0 - 4.9) \cdot \frac{1}{2} + 2 \cdot (2a + 2v_0 + x_0 - 9.8) \cdot 2 + 2 \cdot (\frac{9a}{2} + 3v_0 + x_0 - 14.3) \cdot \frac{9}{2} + 2 \cdot (8a + 4v_0 + x_0 - 21.2) \cdot 8 + 2 \cdot (\frac{25a}{2} + 5v_0 + x_0 - 25.7) \cdot \frac{25}{2} = 0 \\
\frac{\partial d(\mathbf{r}, \mathbf{s})}{\partial v_0} = 2 \cdot (\frac{a}{2} + v_0 + x_0 - 4.9) + 2 \cdot (2a + 2v_0 + x_0 - 9.8) \cdot 2 + 2 \cdot (\frac{9a}{2} + 3v_0 + x_0 - 14.3) \cdot 3 + 2 \cdot (8a + 4v_0 + x_0 - 21.2) \cdot 4 + 2 \cdot (\frac{25a}{2} + 5v_0 + x_0 - 25.7) \cdot 5 = 0 \\
\frac{\partial d(\mathbf{r}, \mathbf{s})}{\partial x_0} = 2 \cdot (\frac{a}{2} + v_0 + x_0 - 4.9) + 2 \cdot (2a + 2v_0 + x_0 - 9.8) + 2 \cdot (\frac{9a}{2} + 3v_0 + x_0 - 14.3) + 2 \cdot (8a + 4v_0 + x_0 - 21.2) + 2 \cdot (\frac{25a}{2} + 5v_0 + x_0 - 25.7) = 0
\end{cases}
$$

Rezolvarea acestui sistem este lăsată ca exercițiu pentru cititor.
